import { getGameConfig } from '@/lib/data';
import { pageDateIso } from '@/data/pageDates';

/**
 * UTC-safe display formatting for an ISO date.
 *
 * ⚠️ Defined here on purpose: pageDates.ts is auto-generated by gen-content-dates.mjs and must
 * never be hand-edited, so a caller that needs to format an *overridden* date cannot rely on the
 * generated `pageDateFormatted(path)` helper. Behaviour is deliberately identical to the
 * generator's formatter — fixed UTC parsing, never the viewer's timezone — so a date can never
 * render one day off for a visitor west of the site's reference meridian.
 */
function formatDisplayDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

interface AuthorBannerProps {
  /** Route key matching pageDates.ts (e.g. "/wiki", "/dungeons/[slug]"). */
  path?: string;
  /** Optional byline override. Defaults to config.author.name — there is NO "Team" fallback. */
  authorName?: string;
  /** Optional avatar initials override (person entity only). */
  authorInitials?: string;
  /** Optional explicit date override; defaults to the Git-derived page content date. */
  date?: string;
  className?: string;
}

/**
 * Author attribution & content-freshness component (single mount point per page).
 *
 * Two legitimate byline modes — the deciding factor is ACCOUNTABILITY, not whether a
 * human name is present:
 * - organization (default): author = the site's own Organization. Legitimate for fan sites
 *   with no verifiable professional identity. Requires /about/ to state who maintains it,
 *   how things are verified, and how to make contact.
 * - person: author = a named Person WITH verifiable identity anchors (sameAs). A short
 *   pen name wearing a "Founder & Lead Editor" title with zero anchors is identity theater
 *   and is worse than an honest organization byline.
 *
 * The publisher Organization must be named after the SITE brand — never the game or its
 * developer — and fan sites must carry a machine-readable "not affiliated" declaration.
 */
export default function AuthorBanner({
  path,
  authorName,
  authorInitials,
  date,
  className = '',
}: AuthorBannerProps) {
  const config = getGameConfig();
  const route = path || '/';
  const iso = date || pageDateIso(route);
  // ⚠️ Display text MUST be derived from `iso`, never from `route`. Reading
  // `pageDateFormatted(route)` here made an explicit `date` override apply to the
  // <time dateTime> attribute and the JSON-LD `dateModified` only, so the badge printed one day
  // while the machine-readable date published another. No build gate can see that mismatch.
  const formatted = formatDisplayDate(iso);

  // 🚫 Never fall back to `${config.game.name} Team` — that default is exactly why dozens of
  // sites shipped with an unattributable byline. Missing attribution must fail loudly.
  const author = config.author;
  if (!author?.name) {
    throw new Error(
      '[AuthorBanner] config.author.name is missing. Configure an accountable byline: the site Organization (recommended for fan sites) or a named Person with verifiable anchors.'
    );
  }

  const isOrgEntity = (author.entity ?? 'organization') === 'organization';
  const resolvedAuthor = authorName || author.name;
  const resolvedInitials =
    authorInitials ||
    (() => {
      const words = String(author.name).trim().split(/\s+/).filter(Boolean);
      const monogram =
        words.length > 1
          ? words.slice(0, 2).map((w: string) => w[0]).join('')
          : String(author.name).slice(0, 2);
      return monogram.toUpperCase();
    })();

  const entityGraph = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': `${config.seo.baseUrl}/#organization`,
        // ✅ site brand — ❌ never config.game.name / config.game.developer
        name: author.org || config.seo.siteName,
        url: config.seo.baseUrl,
        ...(author.description ? { description: author.description } : {}),
        // Fan sites: machine-readable "unofficial" declaration (prevents affiliation misreads).
        ...(author.disambiguatingDescription
          ? { disambiguatingDescription: author.disambiguatingDescription }
          : {}),
        // Accountability triple: editorial principles + contact + non-official declaration.
        ...(config.seo.baseUrl ? { publishingPrinciples: `${config.seo.baseUrl}/about` } : {}),
        ...(config.seo.email ? { email: config.seo.email } : {}),
        // ⚠️ sameAs = this site's own profiles only. Official game/Discord URLs belong to the
        // covered entity and must live in on-page link sections, never in entity identity.
        ...(author.sameAs?.length ? { sameAs: author.sameAs } : {}),
      },
      // Human maintainer as an accountable contact — factual role, no claimed expertise.
      ...(author.maintainer
        ? [
            {
              '@type': 'Person',
              '@id': `${config.seo.baseUrl}/#maintainer`,
              name: author.maintainer,
              jobTitle: author.maintainerRole || 'Site Maintainer',
              url: `${config.seo.baseUrl}/about`,
              worksFor: { '@id': `${config.seo.baseUrl}/#organization` },
            },
          ]
        : []),
    ],
  };

  const webPageSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    // ✅ datePublished should be the first-publish date (a constant); only dateModified tracks content updates.
    dateModified: iso,
  };

  return (
    <aside
      aria-label="Author attribution and freshness"
      className={`inline-flex max-w-full items-center gap-2.5 sm:gap-3 rounded-full border border-white/10 bg-zinc-900/90 px-3 sm:px-3.5 py-1.5 shadow-xs backdrop-blur-sm transition-colors ${className}`}
    >
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(entityGraph) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageSchema) }} />

      {/* Circular Document / Editorial Icon Badge
          🚫 严禁使用游戏图标 / Favicon 充当头像（防伪充官方） */}
      <div className="w-7 h-7 sm:w-7.5 sm:h-7.5 rounded-full bg-amber-500/15 border border-amber-500/30 flex items-center justify-center text-amber-400 shrink-0">
        <svg
          width="13"
          height="13"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
          <polyline points="14 2 14 8 20 8" />
          <line x1="16" x2="8" y1="13" y2="13" />
          <line x1="16" x2="8" y1="17" y2="17" />
          <line x1="10" x2="8" y1="9" y2="9" />
        </svg>
      </div>

      {/* Author Attribution & Freshness Stack
          🚫 严禁在此组件内附加任何说明性副文本（如 "Content checked against..." / "Verified in-game"），
          保持纯粹的双行胶囊结构：第一行品牌维护者 + 第二行更新日期 */}
      <div className="flex flex-col text-left leading-tight">
        <div className="flex flex-wrap items-center gap-1 text-xs">
          <span className="font-bold text-zinc-100">By</span>
          <span className="font-bold text-amber-400">
            {resolvedAuthor}
          </span>
          {author.maintainer && (
            <>
              <span className="text-[#bbc1cf]" aria-hidden="true">·</span>
              <span className="text-zinc-300 font-medium">
                {author.maintainerRole || 'Site Maintainer'}: {author.maintainer}
              </span>
            </>
          )}
        </div>
        <div className="mt-0.5 flex items-center gap-1 text-xs text-[#bbc1cf]">
          <span>Last updated:</span>
          <time dateTime={iso} className="font-semibold text-zinc-200">
            {formatted}
          </time>
        </div>
      </div>
    </aside>
  );
}
